export interface ProductItem {
  id: string;
  name: string;
  category: "Apples" | "Citrus" | "Berries" | "Tropical" | "Mangoes" | "Bananas" | "Avocados" | "Exotic";
  sku: string;
  desc: string;
  origin: string;
  grade: "Grade A+" | "Grade A" | "Grade B";
  price: number;
  priceStr: string;
  basePrice: number;
  stockKg: number;
  stockStatus: "In Stock" | "Low Stock";
  unit: string;
  freshnessScore: number;
  harvestDate: string;
  image: string;
  isFeatured?: boolean;
  rating: number;
  dealDiscount?: number;
  isNegotiable?: boolean;
}

export const UNIFIED_PRODUCTS: ProductItem[] = [
  {
    id: "fuji-apples",
    name: "Premium Fuji Apples",
    category: "Apples",
    sku: "APP-FUJ-01",
    desc: "Crisp, naturally sweet, and hand-selected from highland orchard harvests.",
    origin: "Batu, Malang",
    grade: "Grade A+",
    price: 45000,
    priceStr: "Rp 45.000",
    basePrice: 35000,
    stockKg: 180,
    stockStatus: "In Stock",
    unit: "/unit",
    freshnessScore: 96,
    harvestDate: "Harvested Yesterday",
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?q=80&w=400&auto=format&fit=crop",
    isFeatured: true,
    rating: 4.9,
    dealDiscount: 15,
    isNegotiable: true,
  },
  {
    id: "granny-smith",
    name: "Granny Smith Apples",
    category: "Apples",
    sku: "APP-GRN-02",
    desc: "Tart, firm, and excellent for gourmet culinary dishes & fresh blends.",
    origin: "Poncokusumo, Malang",
    grade: "Grade A",
    price: 52000,
    priceStr: "Rp 52.000",
    basePrice: 40000,
    stockKg: 45,
    stockStatus: "Low Stock",
    unit: "/unit",
    freshnessScore: 92,
    harvestDate: "Harvested This Morning",
    image: "https://images.unsplash.com/photo-1579613832716-14dce736c473?q=80&w=400&auto=format&fit=crop",
    rating: 4.8,
    dealDiscount: 14,
    isNegotiable: true,
  },
  {
    id: "harumanis-mango",
    name: "Harumanis Mango 143",
    category: "Mangoes",
    sku: "MAN-HRM-03",
    desc: "Aromatic, rich honey sweetness, tree-ripened and AI QC inspected.",
    origin: "Tongas, Probolinggo",
    grade: "Grade A+",
    price: 32000,
    priceStr: "Rp 32.000",
    basePrice: 25000,
    stockKg: 220,
    stockStatus: "In Stock",
    unit: "/unit",
    freshnessScore: 94,
    harvestDate: "Harvested This Morning",
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?q=80&w=400&auto=format&fit=crop",
    isFeatured: true,
    rating: 5.0,
    dealDiscount: 16,
    isNegotiable: true,
  },
  {
    id: "cavendish-banana",
    name: "Super Cavendish Bananas",
    category: "Bananas",
    sku: "BAN-CAV-04",
    desc: "Classic golden peel, uniform grading, and packed with natural energy.",
    origin: "East Lampung",
    grade: "Grade A+",
    price: 22000,
    priceStr: "Rp 22.000",
    basePrice: 16000,
    stockKg: 420,
    stockStatus: "In Stock",
    unit: "/unit",
    freshnessScore: 95,
    harvestDate: "2 days ago",
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?q=80&w=400&auto=format&fit=crop",
    rating: 4.9,
    isNegotiable: false,
  },
  {
    id: "hass-avocado",
    name: "Organic Hass Avocados",
    category: "Avocados",
    sku: "AVO-HAS-05",
    desc: "Rich, nutty flavor with an ultra-creamy texture. Harvested at peak ripeness.",
    origin: "Sukabumi Orchards",
    grade: "Grade A+",
    price: 45000,
    priceStr: "Rp 45.000",
    basePrice: 34000,
    stockKg: 35,
    stockStatus: "Low Stock",
    unit: "/unit",
    freshnessScore: 93,
    harvestDate: "Yesterday Evening",
    image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?q=80&w=400&auto=format&fit=crop",
    isFeatured: true,
    rating: 4.9,
    dealDiscount: 16,
    isNegotiable: true,
  },
  {
    id: "valencia-orange",
    name: "Valencia Sweet Oranges",
    category: "Citrus",
    sku: "ORG-VAL-06",
    desc: "Juicy, high vitamin-C content, ideal for bulk commercial fresh pressing.",
    origin: "Berastagi Highlands",
    grade: "Grade A",
    price: 32000,
    priceStr: "Rp 32.000",
    basePrice: 24000,
    stockKg: 310,
    stockStatus: "In Stock",
    unit: "/unit",
    freshnessScore: 90,
    harvestDate: "Harvested This Morning",
    image: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?q=80&w=400&auto=format&fit=crop",
    rating: 4.7,
    isNegotiable: true,
  },
  {
    id: "premium-strawberry",
    name: "Premium Strawberries",
    category: "Berries",
    sku: "BER-STR-07",
    desc: "Plump, vibrant red, and naturally sweet highland strawberries.",
    origin: "Ciwidey Highland",
    grade: "Grade A+",
    price: 85000,
    priceStr: "Rp 85.000",
    basePrice: 65000,
    stockKg: 150,
    stockStatus: "In Stock",
    unit: "/unit",
    freshnessScore: 98,
    harvestDate: "Harvested This Morning",
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?q=80&w=400&auto=format&fit=crop",
    isFeatured: true,
    rating: 4.9,
    isNegotiable: false,
  },
  {
    id: "honeygold-pineapple",
    name: "Honeygold Pineapple",
    category: "Tropical",
    sku: "PIN-HNY-08",
    desc: "Exceptionally sweet core, practically zero acidity, ready to slice.",
    origin: "Subang Estates",
    grade: "Grade A",
    price: 55000,
    priceStr: "Rp 55.000",
    basePrice: 42000,
    stockKg: 90,
    stockStatus: "In Stock",
    unit: "/unit",
    freshnessScore: 91,
    harvestDate: "Harvested Yesterday",
    image: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?q=80&w=400&auto=format&fit=crop",
    rating: 4.8,
    isNegotiable: false,
  },
  {
    id: "red-dragon-fruit",
    name: "Organic Red Dragon Fruit",
    category: "Exotic",
    sku: "DRA-RED-09",
    desc: "Intense magenta pulp, antioxidant rich, naturally sweet and farm fresh.",
    origin: "Banyuwangi Estates",
    grade: "Grade A+",
    price: 26000,
    priceStr: "Rp 26.000",
    basePrice: 19000,
    stockKg: 80,
    stockStatus: "In Stock",
    unit: "/unit",
    freshnessScore: 92,
    harvestDate: "Harvested Yesterday",
    image: "https://images.unsplash.com/photo-1527325678964-54921661f888?q=80&w=400&auto=format&fit=crop",
    rating: 4.8,
    isNegotiable: false,
  },
  {
    id: "sungold-kiwi",
    name: "SunGold Kiwi",
    category: "Exotic",
    sku: "KIW-GLD-10",
    desc: "Sweet golden flesh with smooth skin, rich in vitamins and refreshing flavor.",
    origin: "New Zealand Import Batch",
    grade: "Grade A",
    price: 65000,
    priceStr: "Rp 65.000",
    basePrice: 50000,
    stockKg: 95,
    stockStatus: "In Stock",
    unit: "/unit",
    freshnessScore: 96,
    harvestDate: "2 days ago",
    image: "https://images.unsplash.com/photo-1585059895524-72359e06133a?q=80&w=400&auto=format&fit=crop",
    rating: 4.9,
    isNegotiable: false,
  },
];

export const PRODUCT_CATEGORIES = [
  "All Fruits",
  "Apples",
  "Citrus",
  "Berries",
  "Tropical",
  "Mangoes",
  "Bananas",
  "Avocados",
  "Exotic",
] as const;
